language: node_js
node_js:
  - '0.10'
  - '0.12'
  - stable

before_script:
  - npm install -g bower
  - npm install
  - bower install


before_install:
  - sudo pip install codecov

after_success:
  - codecov